repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-push]
      - id: end-of-file-fixer
        stages: [pre-push]
      - id: check-yaml
        stages: [pre-push]
      - id: check-toml
        stages: [pre-push]
      - id: check-json
        stages: [pre-push]
      - id: check-merge-conflict
        stages: [pre-push]
      - id: check-added-large-files
        args: ['--maxkb=1000']
        stages: [pre-push]
      - id: debug-statements
        stages: [pre-push]
      - id: check-docstring-first
        stages: [pre-push]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      # Run the linter - matches GitHub Actions
      - id: ruff
        args: []
        files: ^(src|tests)/
        stages: [pre-push]
      # Run the formatter - matches GitHub Actions
      - id: ruff-format
        args: [--check]
        files: ^(src|tests)/
        stages: [pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
        args: [--show-error-codes]
        files: ^src/stripje/
        stages: [pre-push]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, src/, -c, pyproject.toml]
        additional_dependencies: ["bandit[toml]", "pbr"]
        files: ^src/
        pass_filenames: false
        stages: [pre-push]

  - repo: local
    hooks:
      - id: pytest-quick
        name: tests
        entry: uv
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-push]
        args: ["run", "--group", "testing", "pytest"]
