name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggers

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Update dependencies
      run: |
        # Update lockfile
        uv lock --upgrade

        # Check if there are changes
        if git diff --quiet uv.lock; then
          echo "No dependency updates available"
          exit 0
        fi

    - name: Run tests
      run: |
        uv sync --extra dev
        uv run pytest tests/test_fast_pipeline.py tests/test_integration.py -v

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "deps: update dependencies"
        title: "🔄 Update dependencies"
        body: |
          ## Dependency Updates

          This PR updates project dependencies to their latest compatible versions.

          ### Changes
          - Updated `uv.lock` with latest dependency versions

          ### Testing
          - ✅ Core functionality tests pass
          - ✅ Integration tests pass

          Auto-generated by GitHub Actions.
        branch: update-dependencies
        delete-branch: true
